apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ubuntu
  namespace: ingress-nginx
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ inventory_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: ingress-nginx
          servicePort: 80
---
