- name: check if kubernetes setup
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: etc_kubernetes

- name: join kubernetes cluster
  shell: "{{ lookup('env', 'secrets.kubeadm_join_command') }}"
  when: not etc_kubernetes.stat.exists
  register: join_output
- debug:
    msg: "{{join_output}}"
- local_action:
    module: copy
    content: "{}"
    dest: "{{ lookup('env', 'OUTPUT_PATH') }}"
  become: False
