- name: ssh access
  ec2_group:
    name: box
    description: sg with rule descriptions
    vpc_id: "{{ vpc }}"
    region: eu-west-2
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ me }}"
    rules_egress:
        - proto: tcp
          from_port: 22
          to_port: 22
          group_id: sg-0cdaf37e873bc998e

- name: Provision a set of instances
  ec2:
     key_name: "vvv-sam-n550jv"
     group: box
     instance_type: t2.nano
     image: "{{ ami_id }}"
     region: "{{ region }}"
     wait: true
     exact_count: 2
     count_tag:
        Name: worker
     instance_tags:
        Name: worker
  register: ec2

- ec2_instance_facts:
    filters:
      "tag:Name": worker
  register: facts
  
- name: write instance infos
  debug:
    msg: "{{ facts | json_query('instances[*].public_dns_name') }}"
    
- local_action:
    module: copy
    content: "{\"workers\": {{ facts | json_query('instances[*].public_dns_name') }}
    }"
    dest: "{{ lookup('env', 'OUTPUT_PATH') }}"