- name: update apt
  apt:
    update_cache: yes

- name: install java
  package:
    name: openjdk-11-jdk
    state: present

- name: install snapd
  package:
    name: snapd
    state: present

- name: install unzip
  package:
    name: unzip
    state: present

- name: install jq
  snap:
    name: jq
    state: present

- name: Download terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip
    dest: /tmp/terraform_0.12.9_linux_amd64.zip
    mode: '0440'
    checksum: sha256:69712c6216cc09b7eca514b9fb137d4b1fead76559c66f338b4185e1c347ace5

- name: Extract terraform
  unarchive:
    src: /tmp/terraform_0.12.9_linux_amd64.zip
    remote_src: yes
    dest: /usr/local/bin

- name: Download packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.4.3/packer_1.4.3_linux_amd64.zip
    dest: /tmp/packer_1.4.3_linux_amd64.zip
    mode: '0440'
    checksum: sha256:c89367c7ccb50ca3fa10129bbbe89273fba0fa6a75b44e07692a32f92b1cbf55

- name: Extract packer
  unarchive:
    src: /tmp/packer_1.4.3_linux_amd64.zip
    remote_src: yes
    dest: /usr/local/bin

- name: Download gradle
  get_url:
    url: https://services.gradle.org/distributions/gradle-6.0.1-bin.zip
    dest: /tmp/gradle-6.0.1-bin.zip
    mode: '0440'
    checksum: sha256:d364b7098b9f2e58579a3603dc0a12a1991353ac58ed339316e6762b21efba44
    timeout: 360

- name: Extract gradle
  unarchive:
    src: /tmp/gradle-6.0.1-bin.zip
    remote_src: yes
    dest: /usr/local/

- name: Extract gradle
  shell: cp -r /usr/local/gradle-6.0.1/bin/* /usr/local/bin

- name: Extract gradle libs
  shell: cp -r /usr/local/gradle-6.0.1/lib/* /usr/local/lib

- file:
    path: /etc/localtime
    state: absent

- name: fix timezone
  shell: ln -s /usr/share/zoneinfo/Europe/London /etc/localtime

- name: update time
  shell: "timedatectl set-ntp off ; timedatectl set-ntp on"

- name: terraform plugin directory
  file:
    path: /home/{{ ansible_user }}/.terraform.d/plugins
    state: directory

- name: download aws provider
  get_url:
    url: https://releases.hashicorp.com/terraform-provider-aws/2.39.0/terraform-provider-aws_2.39.0_linux_amd64.zip
    dest: /tmp/terraform-provider-aws_2.39.0_linux_amd64.zip
    mode: '0440'

- name: create plugins directory
  file:
    path: "/home/{{ ansible_user }}/.terraform.d/plugins/linux_amd64"
    state: directory

- name: Extract aws provider
  unarchive:
    src: /tmp/terraform-provider-aws_2.39.0_linux_amd64.zip
    remote_src: yes
    dest: /home/{{ ansible_user }}/.terraform.d/plugins/linux_amd64

- name: download template provider
  get_url:
    url: https://releases.hashicorp.com/terraform-provider-template/2.1.2/terraform-provider-template_2.1.2_linux_amd64.zip
    dest: /tmp/terraform-provider-template_2.1.2_linux_amd64.zip
    mode: '0440'

- name: Extract template provider
  unarchive:
    src: /tmp/terraform-provider-template_2.1.2_linux_amd64.zip
    remote_src: yes
    dest: /home/{{ ansible_user }}/.terraform.d/plugins/linux_amd64

- name: install chef
  shell: "wget -O- https://opscode.com/chef/install.sh | sudo bash"

- name: install inspec
  apt:
    deb: https://packages.chef.io/files/stable/inspec/4.18.0/ubuntu/18.04/inspec_4.18.0-1_amd64.deb

- name: install python3
  package:
    name: python3
    state: present

- name: install python3
  package:
    name: python3-pip
    state: present

- pip:
    name: ansible

- local_action:
    module: copy
    content: "{}"
    dest: "{{ lookup('env', 'OUTPUT_PATH') }}"
