- name: install java
  package:
    name: openjdk-11-jdk
    state: present

- name: install snapd
  package:
    name: snapd
    state: present

- name: install unzip
  package:
    name: unzip
    state: present

- name: install jq
  snap:
    name: jq
    state: present

- name: Download terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip
    dest: /tmp/terraform_0.12.9_linux_amd64.zip
    mode: '0440'

- name: Extract terraform
  unarchive:
    src: /tmp/terraform_0.12.9_linux_amd64.zip
    remote_src: yes
    dest: /usr/local/bin

- name: Download packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.4.3/packer_1.4.3_linux_amd64.zip
    dest: /tmp/packer_1.4.3_linux_amd64.zip
    mode: '0440'

- name: Extract packer
  unarchive:
    src: /tmp/packer_1.4.3_linux_amd64.zip
    remote_src: yes
    dest: /usr/local/bin

- name: Download gradle
  get_url:
    url: https://services.gradle.org/distributions/gradle-5.6.3-bin.zip
    dest: /tmp/gradle-5.6.3-bin.zip
    mode: '0440'

- name: Extract gradle
  unarchive:
    src: /tmp/gradle-5.6.3-bin.zip
    remote_src: yes
    dest: /usr/local/

- name: Extract gradle
  shell: cp -r /usr/local/gradle-5.6.3/bin/* /usr/local/bin

- name: Extract gradle libs
  shell: cp -r /usr/local/gradle-5.6.3/lib/* /usr/local/lib

- file:
    path: /etc/localtime
    state: absent

- name: fix timezone
  shell: ln -s /usr/share/zoneinfo/Europe/London /etc/localtime

- name: update time
  shell: "timedatectl set-ntp off ; timedatectl set-ntp on"

- name: terraform plugin directory
  file:
    path: /home/{{ ansible_user }}/.terraform.d/plugins
    state: directory

- name: install chef
  shell: "wget -O- https://opscode.com/chef/install.sh | sudo bash"

- name: install inspec
  apt:
    deb: https://packages.chef.io/files/stable/inspec/4.18.0/ubuntu/18.04/inspec_4.18.0-1_amd64.deb

- local_action:
    module: copy
    content: "{}"
    dest: "{{ lookup('env', 'OUTPUT_PATH') }}"
