- name: Upgrade all packages to the latest version
  apt:
    update_cache: yes
    name: "*"
    state: latest

- name: install packages
  package: "{{ item }}"
  with_items:
  - nginx
  - dnsutils

- name: install gpg
  package:
    name: gpg

- name: install gpg-agent
  package:
    name: gpg-agent

- name: Add docker key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

# https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
- name: disable swap
  shell: swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Ensure swap disabled
  lineinfile:
    path: /etc/sysctl.conf
    line: "vm.swappiness = 0"

- name: update apt
  apt:
    update_cache: yes

- name: install docker
  package:
    name: docker.io
    state: present

- name: setup docker to start
  systemd:
    name: docker.service
    enabled: yes
    state: started

- name: install apt-transport-https
  package:
    name: apt-transport-https
    state: present

- name: install kubernetes binaries
  package:
    name: "{{ item }}"
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: check if kubernetes setup
  stat:
    path: /etc/kubernetes/admin.conf
  register: etc_kubernetes

- name: create kubernetes master
  shell: kubeadm init --apiserver-advertise-address {{ ansible_default_ipv4.address }}
  register: kubdadm_init
  when: not etc_kubernetes.stat.exists
- debug: var=kubdadm_init.stdout_lines

- name: create kube config directory
  file:
    state: directory
    path: "~/.kube"
  become: false

- name: copy cluster configuration
  shell: "sudo cp /etc/kubernetes/admin.conf ~/.kube/config"

- name: correct group of kubernetes cluster config file
  shell: "sudo chown $(id -u):$(id -g) ~/.kube/config"
  become: false

- name: install networking
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  become: false

- name: create join command
  shell: "kubeadm token create --print-join-command"
  register: join_command
- debug: var=join_command.stdout_lines

- name: install postgres
  package:
    name: postgresql
    state: present

- local_action:
    module: copy
    content: "{\"secrets\": {\"kubeadm_join_command\": {{ join_command.stdout | to_json }} } }"
    dest: "{{ lookup('env', 'OUTPUT_PATH') }}"
  become: false
